### ISSUE TITLE
[Question] checkUrlIs does not ignore query parameters? (and are there negated helper methods?)

### ISSUE THREAD

**Issue by michaelklopf** [Arcesilas/active-state#11]
Hi,

I just noticed that

`https://test.localhost/notifications`

and 

`https://test.localhost/notifications?all=1`

return for 

`{{ active_url_is('notifications') }}`

both the `active` string.

May it be that query params are not part of the exact url check? I would like to differentiate between the path without and with query parameters. Is there something for that use case?

In the lib at line https://github.com/Arcesilas/active-state/blob/633d1ba603c89f5d3bdffdb7d0f225c34df1c333/src/Active.php#L57 the Laravel HTTP Request is() method is used. The Laravel `is()` method makes use of a string comparison with http://php.net/manual/en/function.rawurldecode.php at https://github.com/laravel/framework/blob/2906b572aa83ff46b8ad57093dd0e859c0ff783f/src/Illuminate/Http/Request.php#L148

And if I see that right, the url should be the whole thing.

**Comment by Arcesilas** [comment]
Hi, thanks for your feedback!

I understand... Actually, the problem is that I've named the methods with `url`, while I should have named them with `path`, since in Laravel, the `Request::is()` method checks the path.

To achieve what you want to do, you should use one of the `active_query_*` helpers. If you also need to check the path, then it becomes a little more tricky, since you need to check two functions results. You could then create a custom helper, something like:

```php
    function active_full_url_is($url, $query)
    {
        $activeState = app('active-state');
        if ($activeState->checkUrlIs($url) && $activeState->checkQueryIs($query))  {
            return $activeState->getActiveValue();
        }
        return $activeState->getInactiveValue();
    }
```
_(code not tested)_

I may consider renaming `checkUrl*` and `ifUrl*` methods to more explicit `checkPath*` and `ifPath*` (and mark the former ones as obsolete), and add some `checkFullUrl*` methods, with appropriate helpers and blade directives.

**Comment by michaelklopf** [comment]
Thank you for the assistance. I think I would need something to check if the url is coming without any query params, but I will leave it at that. Good recommendation though.

I went back to the original problem, which is that I don't have a sufficient helper function for the Blades and the directives are not as elegant as we would like them to be.

The example is that I want list items as active or inactive depending on the query param.

The solution would be something like:

```html
<li class="tw-o-list-separated__item  {{ active_query_has_not('all') }}">
```
....
```html
<li class="tw-o-list-separated__item  {{ active_query_has('all') }}">
```

Which looks more elegant than:

```html
<li class="tw-o-list-separated__item @not_query_has('all') active @endnot_query_has ">
```

I forked the library and added a PR with the additions for the helper above to see a working example -> https://github.com/michaelklopf/active-state/pull/1/files

Would you consider adding helpers like that?

**Comment by Arcesilas** [comment]
Also, I perfectly understand that the names are not the most elegant, but I have chosen them to follow a consistent naming convention. 
I prefer comething like "query_contains" and "not_query_contains" (like in ! query_contains) rather than query_does_not_contain, and other names with negation following english grammar like query_is_not. Every method has its opposite with `not_` prefixed, which is the most consistent I could do.

If a function/method name does not fit your needs, you can simply extend the `Active` class and use the names you want. It requires a little configuration, but it's not such a big deal when working on a project: disable Laravel's automatic service provider registration, use your own provider and extend the `Active` class.

What do you think?

**Comment by michaelklopf** [comment]
Hey, your naming scheme is no problem. Only the helper functions work better in Blade than the directives. No tags, only curly braces.

Hmm, I've to look into extending the class myself, I'll see if I find a fitting solution.

**Comment by Arcesilas** [comment]
Ok sorry, did not understand werll what you where meaning. I did not notice in your example you used the helpers, which you consider more elegant than the blade directives (and you're right about that!).

Helpers are simple functions, you don't need to extends anything, actually, just declare them in a file and include it (with Composer, which is the recommanded way).

In your fork, you add a method to `Active` class and use it in a new helper, if I see it well.
Since your method is just the negative of another, you don't need it... just write your helper function:
```php
    function active_query_has_not(...$parameters)
    {
        return ! app('active-state')->ifQueryHas(...$parameters);
    }
```

You don't need anything more, actually...

**Comment by michaelklopf** [comment]
The problem is your ifQueryHas calls the check method, which calls the getState method and that one is returning the string `active` which I want to use here as a class name. Negating after the helper call is resulting in `1` appearing here because the negation of a string is the boolean value true.

A working helper method would be this one, which makes use of your internals:

```php
function active_query_has_not(...$parameters)
{
    $hasNoMatch = !call_user_func_array([app('active-state'), 'checkQueryHas'], $parameters);
    return app('active-state')->getState($hasNoMatch);
}
```

**Comment by Arcesilas** [comment]
I'm definitely going to work on a new major version and rethink these problems. Thanks for your messages.

**Comment by Arcesilas** [comment]
Hi @michaelklopf 

Would you mind having a look at [v3 branch](https://github.com/Arcesilas/active-state/tree/v3)?
Changes are listed in the [Changelog](https://github.com/Arcesilas/active-state/blob/v3/CHANGELOG.md#unreleased).

The most important, I think, are the `ifNot*` and `checkNot*` methods, which give more flexibility when you need to write custom helpers. Note that appropriate helpers have also been added.

**Comment by michaelklopf** [comment]
Hey @Arcesilas,

I got your branch and swapped in `active_not_query_has` and it works as promised. The rest of the app is working fine too.

Well done 👍🏻

**Comment by Arcesilas** [comment]
Great! Thanks for your feedback!

I think it's not a new major, actually, but rather a new minor v2.x version since there is no BC break. I will release it very soon.
