### ISSUE TITLE
Active::checkRouteIs() with array of routes

### ISSUE THREAD

**Issue by Arcesilas** [Arcesilas/active-state#9]
Currently, `Active::checkRouteIs()` accepts an array of routes, but the format of the array is a little complex, in my opinion, for an actual use in a view:

```php
[
    'some.route' => ['slug' => 'something'],
    'route.test' => ['slug' => 'title']
]
```

@marcelogarbin do you think this usage is relevant?

Personnally, I think it's not really usable in a view and am considering to remove this functionnality. What do you think?

**Comment by Arcesilas** [comment]
Hi, thanks for your answer and your feedback in a general manner! Don't worry about the delay, there is no hurry!

I'm considering releasing a V3.0 of the package with:
- cache (no idea how to add this feature yet...)
- tests entirely rewritten using [orchestra/testbench](https://github.com/orchestral/testbench)
- full [type hint](https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration)

The `checkRouteIs()` method will then not allow anymore an array of route names: `checkRouteIn()` should be used for that (and I think you should use it instead of `checkRouteIs()` since it's probably faster). `checkRouteIs()` is more complex because it has to resolve the routes urls (with the route parameters) to compare the url, whereas `checkRouteIn()` simply compares the names (therefore it should be used if you just need to check the route name) :arrow_right:  I will add this information to the documentation.

**Comment by marcelogarbin** [comment]
Perfect, I confess I have no knowledge about automated testing yet. But I would like to study more about it.

On doing the `checkRouteIs()` method switch to `checkRouteIn()`, I'll do this as soon as possible. I believe that I stopped changing this method, because it was working and I did not have to. I only found it because I did a search in 3 projects, I found only 1.

So by me, I agree with the change you make in the package.
